region          = "us-east-1"
vpc_cidr        = "10.0.0.0/16"
vpc_name        = "my-vpc"
subnet_az       = ["us-east-1a", "us-east-1b"]
pub_subnet_cidr = ["10.0.1.0/24", "10.0.2.0/24"]
pri_subnet_cidr = ["10.0.3.0/24", "10.0.4.0/24"]
pub_subnet_name = ["public-subnet-1", "public-subnet-2"]
pri_subnet_name = ["subnet-1", "subnet-2"]
public_rt_name  = "public-rt"
private_rt_name = "private-rt"
igw_name        = "igw"
enable_vpc_logs      = true
vpc_flow_log_s3_name = "vpc_flow_log"
vpc-flow-logs-role ="dev-vpc-flow-logs-role"
